site:
  title: My Awesome Website
  description: A prototype showing how to use GitHub as a CMS
  url: https://lqdev.github.io/TestGHCMS
  author:
    name: John Doe
    email: john@doe.com
    url: https://lqdev.github.io/TestGHCMS
  language: en
postTypes:
  article:
    enabled: true
    permalink: '/articles/{{ page.date | date: ''%Y/%m/%d'' }}/{{ page.fileSlug }}/'
    layout: article
  note:
    enabled: true
    permalink: '/notes/{{ page.date | date: ''%Y/%m/%d'' }}/{{ page.fileSlug }}/'
    layout: note
  response:
    enabled: true
    permalink: '/responses/{{ page.date | date: ''%Y/%m/%d'' }}/{{ page.fileSlug }}/'
    layout: response
  bookmark:
    enabled: true
    permalink: '/bookmarks/{{ page.date | date: ''%Y/%m/%d'' }}/{{ page.fileSlug }}/'
    layout: bookmark
  media:
    enabled: true
    permalink: '/media/{{ page.date | date: ''%Y/%m/%d'' }}/{{ page.fileSlug }}/'
    layout: media
  review:
    enabled: true
    permalink: '/reviews/{{ page.date | date: ''%Y/%m/%d'' }}/{{ page.fileSlug }}/'
    layout: review
features:
  discussions:
    enabled: true
    autoCreate: true
  webmentions:
    enabled: false
    send: true
    receive: true
    endpoint: https://webmention.io/api/mentions.jf2
  microformats:
    enabled: true
  rss:
    enabled: true
  sitemap:
    enabled: true
theme:
  style: minimal
  colorScheme: light
  accentColor: '#0969da'
  font:
    body: system-ui, -apple-system, sans-serif
    heading: system-ui, -apple-system, sans-serif
    mono: ui-monospace, monospace
navigation:
  - title: Home
    url: /
  - title: Articles
    url: /articles/
  - title: Notes
    url: /notes/
  - title: Responses
    url: /responses/
  - title: Bookmarks
    url: /bookmarks/
  - title: Media
    url: /media/
  - title: Reviews
    url: /reviews/
  - title: About
    url: /about/
social:
  github: ''
  mastodon: ''
  bluesky: ''
  twitter: ''
