name: Setup Repository Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync labels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');

            // Read labels configuration
            const labelsConfig = yaml.load(
              fs.readFileSync('.github/labels.yml', 'utf8')
            );

            // Get existing labels
            const { data: existingLabels } =
              await github.rest.issues.listLabelsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

            const existingLabelNames = existingLabels.map(l => l.name);

            // Create or update labels
            for (const label of labelsConfig) {
              if (existingLabelNames.includes(label.name)) {
                // Update existing label
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  description: label.description,
                  color: label.color,
                });
                console.log(`Updated label: ${label.name}`);
              } else {
                // Create new label
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  description: label.description,
                  color: label.color,
                });
                console.log(`Created label: ${label.name}`);
              }
            }

            console.log('Label sync completed successfully!');
